name: Mixed inputs

on:
  workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Read YAML file
      id: read-yaml
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const yaml = require('js-yaml');

          const yamlFilePath = './input.yaml';  // Hardcoded path
          const fileContents = fs.readFileSync(yamlFilePath, 'utf8');
          const data = yaml.load(fileContents);

          console.log(JSON.stringify(data));

          // Set outputs for subsequent steps
          return {
            name: data.name,
            message: data.message,
            use-emoji: data.useEmoji,
            environment: data.environment
          }

    - name: Send greeting
      run: |
        echo "${{ steps.read-yaml.outputs.message }} ${{ steps.read-yaml.outputs.name }}"
