name: Mixed inputs

on:
  workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Read JSON file
      id: read-json
      run: |
        cat inputs.json  # Display contents of the input.json file for verification
        echo "::set-output name=data::$(cat inputs.json | jq -r '.')"
      shell: bash
      
    - name: Set outputs
      id: set-outputs
      run: |
        echo "::set-output name=name::$(echo '${{ steps.read-json.outputs.data }}' | jq -r '.name')"
        echo "::set-output name=message::$(echo '${{ steps.read-json.outputs.data }}' | jq -r '.message')"
        echo "::set-output name=use-emoji::$(echo '${{ steps.read-json.outputs.data }}' | jq -r '.use-emoji')"
        echo "::set-output name=environment::$(echo '${{ steps.read-json.outputs.data }}' | jq -r '.environment')"
      shell: bash

    - name: Send greeting
      run: |
        echo "${{ steps.set-outputs.outputs.message }} ${{ steps.set-outputs.outputs.name }}"
