name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      message2:
        required: true
        default: helloooo
      message3:
        required: true
        default: world
      message4:
        required: true
        default: bye
      message5:
        required: true
        default: world
      message6:
        required: true
        default: another message
      message7:
        required: true
      message8:
        required: true
        default: helloooo
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run:  |
        echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
