name: Mixed inputs

on:
  workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Read JSON file
      id: read-json
      run: |
        cat input.json  # Display contents of the input.json file for verification
        echo "name=$(jq -r '.name' input.json)" >> $GITHUB_ENV
        echo "message=$(jq -r '.message' input.json)" >> $GITHUB_ENV
        echo "use_emoji=$(jq -r '.\"use-emoji\"' input.json)" >> $GITHUB_ENV
        echo "environment=$(jq -r '.environment' input.json)" >> $GITHUB_ENV

    - name: Send greeting
      run: |
        echo "${{ env.message }} ${{ env.name }}"

    - name: Call API
      run: |
        response=$(curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"title": "${{ env.name }}", "body": "${{ env.message }}", "userId": 1}' \
          https://jsonplaceholder.typicode.com/posts \
          -w "%{http_code}" \
          -s)
        echo "API Response: $response"
